refactor: split words by language
JonPurvis/profanify pull request #8
Opened 2024-08-07 11:54 UTC by davideprevosto

This Pull Request splits words by language. It also adds a first version of the Italian stop-words configuration.

2024-08-07 20:10 UTC, JonPurvis commented
Hey @davideprevosto 

Would you be able to take a look at the failing static analysis checks? From what I can see:

1) `composer lint` needs running 
2) You've moved the config files into `Config/words/` rather than just `Config/` but when including them, not looking within /words. I think they should just live in `Config/` though like before.

Thanks!

2024-08-07 22:28 UTC, faissaloux commented
@JonPurvis I think the words files should live in a separated directory in Config to separate them from `tolerated` file like @davideprevosto did this directory may have multiple files later on for each language, I'm just thinking to rename the dir `words` to `profanities` 🤔

2024-08-07 22:32 UTC, JonPurvis commented
Ah yes good point @faissaloux, somehow I forgot we had tolerated.php now 😆 (have updated my comment)

Agreed on a directory name change, but how about `lang`?

2024-08-07 22:41 UTC, faissaloux commented
> Agreed on a directory name change, but how about `lang`?

Emmmmm `lang` doesn't represent what's inside. I think `profanities` is better!

If someone gets there will know exactly what `en.php` is for exactly from its directory name (`profanities`)

2024-08-07 22:52 UTC, JonPurvis commented
`profanities` it is 😄

2024-08-07 23:56 UTC, faissaloux requested changes
Can we please make it more flexible to accept more languages by just adding more languages files on the `profanities` directory without adding languages files to the code one by one.

2024-08-07 23:56 UTC, faissaloux commented on src/Expectations/Profanity.php
> +        );
```suggestion
        $words = [];
        $profanitiesDir = __DIR__.'/../Config/profanities';

        if (($profanitiesFiles = scandir($profanitiesDir)) === false) {
            return true;
        }

        $profanitiesFiles = array_diff($profanitiesFiles, ['.', '..']);

        foreach($profanitiesFiles as $profanitiesFile) {
            $words = array_merge(
                $words,
                include "$profanitiesDir/$profanitiesFile"
            );
        }
```

2024-08-11 18:07 UTC, faissaloux requested changes
Can you please add this note `SHOULD ALL WORDS BE lowercase!` to all words files on line 5

2024-08-11 18:07 UTC, faissaloux commented on src/Config/words/it.php
> +return [
```suggestion
// SHOULD ALL WORDS BE lowercase!

return [
```

2024-08-15 22:03 UTC, JonPurvis commented
Hey @davideprevosto 👋 

I'm keen to get this work into the package. Would you have any time soon to action the required changes? If not, I'd be happy to commit to this branch to finish the work off and get it merged 😄

2024-08-16 09:39 UTC, davideprevosto commented
Hi @JonPurvis, I tried to follow your instructions and I pushed a few changes. I run composer lint and I suppose Laravel Pint did its job.

I also run composer test but I run into the following issue, I suppose I need to further investigate what I am doing wrong.

```
composer test
> rector --dry-run
sh: /Users/xxx/Library/Application: No such file or directory
Script rector --dry-run handling the test:refacto event returned with error code 127
Script @test:refacto was called via test
```

2024-08-16 10:05 UTC, JonPurvis commented
Hey @davideprevosto 

Not actually sure what could be causing that error. Do you get the same thing when you run `composer test:refacto`?

2024-08-16 10:09 UTC, davideprevosto commented
> composer test:refacto

Yes @JonPurvis, I am getting the same error

```
composer test:refacto
> rector --dry-run
sh: /Users/xxxx/Library/Application: No such file or directory
Script rector --dry-run handling the test:refacto event returned with error code 127
```

2024-08-16 10:15 UTC, JonPurvis commented
Okay, can you try running `composer test:lint`? I want to see if all of them have the same issue or it's just refacto

2024-08-16 10:17 UTC, davideprevosto commented
> Okay, can you try running `composer test:lint`? I want to see if all of them have the same issue or it's just refacto

<img width="2279" alt="image" src="https://github.com/user-attachments/assets/d230abbd-fc39-4c63-8938-6190f93f5309">

2024-08-16 10:26 UTC, JonPurvis commented
Hmm, that's odd. It works for me even with your changes. Although it does fix one thing:

```php
    FileLineFinder::where(function (string $line) use (&$foundWords): bool {
        return str_contains(strtolower($line), strtolower(array_values($foundWords ?? [])[0]));
    })
```

to

```php
    FileLineFinder::where(function (string $line) use (&$foundWords): bool {
        return str_contains(strtolower($line), strtolower((string) array_values($foundWords ?? [])[0]));
    })
```

If you make that change, and then amend the merge conflict, this branch should be good to merge. I'm not sure why refacto doesn't run properly on your machine 😢

2024-08-16 12:09 UTC, JonPurvis commented
Thanks @davideprevosto 

Are you also able to sort the merge conflict please?

2024-08-16 12:18 UTC, davideprevosto commented
@JonPurvis can you help me with the merge conflict please? 

<img width="911" alt="image" src="https://github.com/user-attachments/assets/6179619b-3069-4f6c-a7d0-45bb203a6b78">

I tried to merge the branch into the master branch (on my fork) without issues.

2024-08-16 12:41 UTC, merged

2024-08-16 12:42 UTC, JonPurvis commented
Thanks for the contribution @davideprevosto 🥳 I'll get a new release tagged later today!